Repository pytroll/trollimage, pull requests merged in 2023-11, with the labels that each got.

#150 Keep the original dtype of the data when stretching
  trollimage/tests/test_image.py
  trollimage/xrimage.py
Labels: enhancement

#151 Preserve dtypes in XRImage "enhancements"
  trollimage/tests/test_image.py
  trollimage/xrimage.py
Labels: enhancement

#148 Add Python 3.12 to CI testing
  .github/workflows/ci.yaml
Labels: dependencies

#153 Fix stretching integer data
  trollimage/tests/test_image.py
  trollimage/xrimage.py
Labels: bug

#154 Fix stretch when min/max value it outside input data type
  doc/examples/utilities-examples.py
  trollimage/tests/test_image.py
  trollimage/utilities.py
  trollimage/xrimage.py
Labels: bug
